version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep infinity"]
    ports:
      - "6667:6667"
    tty: true

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      - server
    tty: true

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      - server
    tty: true